#!/usr/bin/bash
FUNC=$1

#echo $BASH_LIB_PATH

for i in . ${BASH_LIB_PATH//:/ }
do
    FILE=$( grep -le "${FUNC}[ ]*()" $i/* 2>/dev/null | head -n 1 )
    #echo $FILE
    if [ "$FILE" != "" ]
    then
        break
    fi
done

if [ "$FILE" == "" ]
then
    echo -e "\nFunction $FUNC not found\n"
    exit 1
fi
	
DOCSTRING=$( grep -le "##[ ]*DOC $FUNC" $FILE )
if [ $? == 0 ]
then
    DOCCING=0
    while read LINE
    do
        
        if [[ "${LINE:0:2}" == "##" && "${LINE##\#\#DOC }" == "$FUNC" ]]
        then
            echo -e "\n\e[1m$FUNC\e[0m\n"
            DOCCING=1
        
        elif [ $DOCCING == 1 ]
        then
            if [ ${LINE:0:1} == "#" ]
            then
                DOC=${LINE##\#}
                DOC=${DOC# }
                echo $DOC
            else
                DOCCING=0
            fi
        fi

    done < $FILE
    echo
else
    echo -e "\nFunction found in file $FILE, but no documentation found.\n"
fi
# Local Variables:
# mode:shell-script
# sh-shell:bash
# End:

